//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/InputActions/MainInputAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MainInputAction: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MainInputAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MainInputAction"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""7f98fd74-a655-4245-b9f9-6ad744dcfef3"",
            ""actions"": [
                {
                    ""name"": ""Line1Action"",
                    ""type"": ""Button"",
                    ""id"": ""8e6cf81a-f340-45bb-bfc5-edfe870be25f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line2Action"",
                    ""type"": ""Button"",
                    ""id"": ""8a6a2e68-97b8-45ed-98e6-cc98719dce98"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line3Action"",
                    ""type"": ""Button"",
                    ""id"": ""c1d059d6-cde5-4626-8875-68e370ef2e10"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line4Action"",
                    ""type"": ""Button"",
                    ""id"": ""56008391-72e3-4af1-93f2-81e1165a0676"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""989d39c6-5372-4e5c-9515-589be42b8282"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line1Action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fc44ae47-cc47-437b-93cb-a7a1c8323111"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line2Action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2dfa200c-e3fb-4708-bb03-5fb6e355fa78"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line3Action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7ad6e538-9796-4428-90be-b5876cd8a91f"",
                    ""path"": ""<Keyboard>/semicolon"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line4Action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""FreePlay"",
            ""id"": ""590c925e-18c3-46f9-8766-d2c8a355479d"",
            ""actions"": [
                {
                    ""name"": ""ListUp"",
                    ""type"": ""Button"",
                    ""id"": ""ac9f6b25-c588-4d9e-84e3-ac1327f6a869"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ListDown"",
                    ""type"": ""Button"",
                    ""id"": ""d77afe69-8bdb-4cd2-883c-fd08141f3cc6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SongSelect"",
                    ""type"": ""Button"",
                    ""id"": ""ad4de43e-da71-41d5-9b4b-2005d6f77db8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ExitSongList"",
                    ""type"": ""Button"",
                    ""id"": ""4efbf6f8-6044-4898-97a9-09e10f067fde"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpeedUp"",
                    ""type"": ""Button"",
                    ""id"": ""d99ac480-4e45-4522-8501-e6c8657ce879"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpeedDown"",
                    ""type"": ""Button"",
                    ""id"": ""d18f693e-172f-4798-b3f9-7a0261e331e4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ac8d6b32-4144-48de-a9fb-aa67bf43d8a8"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ListUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2d2c44ed-0797-456b-b4ed-29ec16566fbe"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ListUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""db34ef2a-036a-4cbc-bf0e-68b0e0b012c2"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ListDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""367544d0-cf5c-4c8a-9329-744fa009b4a0"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ListDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eae3494f-74ab-4c6e-bd0d-fdefc32c20c5"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SongSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77d24bc5-5941-4b06-8ad9-ecb637d46e94"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SongSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""68c5b8e7-36a9-483d-b260-9dcafff38d48"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ExitSongList"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cfc2d4a4-5e15-4725-8053-cad11d3c6550"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpeedUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e5041ebb-d604-4380-a608-634825715d0c"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpeedDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Menu"",
            ""id"": ""8c010e7f-3da1-4f12-8799-7720b45ccd4f"",
            ""actions"": [
                {
                    ""name"": ""ListUp"",
                    ""type"": ""Button"",
                    ""id"": ""eb683d89-a100-438e-987d-906310c639a9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ListDown"",
                    ""type"": ""Button"",
                    ""id"": ""deaca0ec-e5b1-4c1c-920d-6289d1a1f882"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MenuSelect"",
                    ""type"": ""Button"",
                    ""id"": ""6104eb08-58b1-433a-be5e-605a4ec87b0e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Exit"",
                    ""type"": ""Button"",
                    ""id"": ""d2edbac9-da17-43f1-a554-c335d1105559"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3c663219-368e-47da-af7f-344ef5c79415"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ListUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""abb10ef5-a1d4-4cb3-8301-c63f9bec65e9"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ListUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""867f5caa-ec39-4300-979c-62828ebbf443"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ListDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5bc95a23-40b8-4deb-8818-c4bc1616897f"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ListDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""652dc011-2c93-430a-9210-da2a349ba1c3"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuSelect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""36d80e53-95be-4c2b-9779-87ab85a27844"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Exit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Line1Action = m_Player.FindAction("Line1Action", throwIfNotFound: true);
        m_Player_Line2Action = m_Player.FindAction("Line2Action", throwIfNotFound: true);
        m_Player_Line3Action = m_Player.FindAction("Line3Action", throwIfNotFound: true);
        m_Player_Line4Action = m_Player.FindAction("Line4Action", throwIfNotFound: true);
        // FreePlay
        m_FreePlay = asset.FindActionMap("FreePlay", throwIfNotFound: true);
        m_FreePlay_ListUp = m_FreePlay.FindAction("ListUp", throwIfNotFound: true);
        m_FreePlay_ListDown = m_FreePlay.FindAction("ListDown", throwIfNotFound: true);
        m_FreePlay_SongSelect = m_FreePlay.FindAction("SongSelect", throwIfNotFound: true);
        m_FreePlay_ExitSongList = m_FreePlay.FindAction("ExitSongList", throwIfNotFound: true);
        m_FreePlay_SpeedUp = m_FreePlay.FindAction("SpeedUp", throwIfNotFound: true);
        m_FreePlay_SpeedDown = m_FreePlay.FindAction("SpeedDown", throwIfNotFound: true);
        // Menu
        m_Menu = asset.FindActionMap("Menu", throwIfNotFound: true);
        m_Menu_ListUp = m_Menu.FindAction("ListUp", throwIfNotFound: true);
        m_Menu_ListDown = m_Menu.FindAction("ListDown", throwIfNotFound: true);
        m_Menu_MenuSelect = m_Menu.FindAction("MenuSelect", throwIfNotFound: true);
        m_Menu_Exit = m_Menu.FindAction("Exit", throwIfNotFound: true);
    }

    ~@MainInputAction()
    {
        UnityEngine.Debug.Assert(!m_Player.enabled, "This will cause a leak and performance issues, MainInputAction.Player.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_FreePlay.enabled, "This will cause a leak and performance issues, MainInputAction.FreePlay.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Menu.enabled, "This will cause a leak and performance issues, MainInputAction.Menu.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Line1Action;
    private readonly InputAction m_Player_Line2Action;
    private readonly InputAction m_Player_Line3Action;
    private readonly InputAction m_Player_Line4Action;
    public struct PlayerActions
    {
        private @MainInputAction m_Wrapper;
        public PlayerActions(@MainInputAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @Line1Action => m_Wrapper.m_Player_Line1Action;
        public InputAction @Line2Action => m_Wrapper.m_Player_Line2Action;
        public InputAction @Line3Action => m_Wrapper.m_Player_Line3Action;
        public InputAction @Line4Action => m_Wrapper.m_Player_Line4Action;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Line1Action.started += instance.OnLine1Action;
            @Line1Action.performed += instance.OnLine1Action;
            @Line1Action.canceled += instance.OnLine1Action;
            @Line2Action.started += instance.OnLine2Action;
            @Line2Action.performed += instance.OnLine2Action;
            @Line2Action.canceled += instance.OnLine2Action;
            @Line3Action.started += instance.OnLine3Action;
            @Line3Action.performed += instance.OnLine3Action;
            @Line3Action.canceled += instance.OnLine3Action;
            @Line4Action.started += instance.OnLine4Action;
            @Line4Action.performed += instance.OnLine4Action;
            @Line4Action.canceled += instance.OnLine4Action;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Line1Action.started -= instance.OnLine1Action;
            @Line1Action.performed -= instance.OnLine1Action;
            @Line1Action.canceled -= instance.OnLine1Action;
            @Line2Action.started -= instance.OnLine2Action;
            @Line2Action.performed -= instance.OnLine2Action;
            @Line2Action.canceled -= instance.OnLine2Action;
            @Line3Action.started -= instance.OnLine3Action;
            @Line3Action.performed -= instance.OnLine3Action;
            @Line3Action.canceled -= instance.OnLine3Action;
            @Line4Action.started -= instance.OnLine4Action;
            @Line4Action.performed -= instance.OnLine4Action;
            @Line4Action.canceled -= instance.OnLine4Action;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // FreePlay
    private readonly InputActionMap m_FreePlay;
    private List<IFreePlayActions> m_FreePlayActionsCallbackInterfaces = new List<IFreePlayActions>();
    private readonly InputAction m_FreePlay_ListUp;
    private readonly InputAction m_FreePlay_ListDown;
    private readonly InputAction m_FreePlay_SongSelect;
    private readonly InputAction m_FreePlay_ExitSongList;
    private readonly InputAction m_FreePlay_SpeedUp;
    private readonly InputAction m_FreePlay_SpeedDown;
    public struct FreePlayActions
    {
        private @MainInputAction m_Wrapper;
        public FreePlayActions(@MainInputAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @ListUp => m_Wrapper.m_FreePlay_ListUp;
        public InputAction @ListDown => m_Wrapper.m_FreePlay_ListDown;
        public InputAction @SongSelect => m_Wrapper.m_FreePlay_SongSelect;
        public InputAction @ExitSongList => m_Wrapper.m_FreePlay_ExitSongList;
        public InputAction @SpeedUp => m_Wrapper.m_FreePlay_SpeedUp;
        public InputAction @SpeedDown => m_Wrapper.m_FreePlay_SpeedDown;
        public InputActionMap Get() { return m_Wrapper.m_FreePlay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(FreePlayActions set) { return set.Get(); }
        public void AddCallbacks(IFreePlayActions instance)
        {
            if (instance == null || m_Wrapper.m_FreePlayActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_FreePlayActionsCallbackInterfaces.Add(instance);
            @ListUp.started += instance.OnListUp;
            @ListUp.performed += instance.OnListUp;
            @ListUp.canceled += instance.OnListUp;
            @ListDown.started += instance.OnListDown;
            @ListDown.performed += instance.OnListDown;
            @ListDown.canceled += instance.OnListDown;
            @SongSelect.started += instance.OnSongSelect;
            @SongSelect.performed += instance.OnSongSelect;
            @SongSelect.canceled += instance.OnSongSelect;
            @ExitSongList.started += instance.OnExitSongList;
            @ExitSongList.performed += instance.OnExitSongList;
            @ExitSongList.canceled += instance.OnExitSongList;
            @SpeedUp.started += instance.OnSpeedUp;
            @SpeedUp.performed += instance.OnSpeedUp;
            @SpeedUp.canceled += instance.OnSpeedUp;
            @SpeedDown.started += instance.OnSpeedDown;
            @SpeedDown.performed += instance.OnSpeedDown;
            @SpeedDown.canceled += instance.OnSpeedDown;
        }

        private void UnregisterCallbacks(IFreePlayActions instance)
        {
            @ListUp.started -= instance.OnListUp;
            @ListUp.performed -= instance.OnListUp;
            @ListUp.canceled -= instance.OnListUp;
            @ListDown.started -= instance.OnListDown;
            @ListDown.performed -= instance.OnListDown;
            @ListDown.canceled -= instance.OnListDown;
            @SongSelect.started -= instance.OnSongSelect;
            @SongSelect.performed -= instance.OnSongSelect;
            @SongSelect.canceled -= instance.OnSongSelect;
            @ExitSongList.started -= instance.OnExitSongList;
            @ExitSongList.performed -= instance.OnExitSongList;
            @ExitSongList.canceled -= instance.OnExitSongList;
            @SpeedUp.started -= instance.OnSpeedUp;
            @SpeedUp.performed -= instance.OnSpeedUp;
            @SpeedUp.canceled -= instance.OnSpeedUp;
            @SpeedDown.started -= instance.OnSpeedDown;
            @SpeedDown.performed -= instance.OnSpeedDown;
            @SpeedDown.canceled -= instance.OnSpeedDown;
        }

        public void RemoveCallbacks(IFreePlayActions instance)
        {
            if (m_Wrapper.m_FreePlayActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IFreePlayActions instance)
        {
            foreach (var item in m_Wrapper.m_FreePlayActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_FreePlayActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public FreePlayActions @FreePlay => new FreePlayActions(this);

    // Menu
    private readonly InputActionMap m_Menu;
    private List<IMenuActions> m_MenuActionsCallbackInterfaces = new List<IMenuActions>();
    private readonly InputAction m_Menu_ListUp;
    private readonly InputAction m_Menu_ListDown;
    private readonly InputAction m_Menu_MenuSelect;
    private readonly InputAction m_Menu_Exit;
    public struct MenuActions
    {
        private @MainInputAction m_Wrapper;
        public MenuActions(@MainInputAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @ListUp => m_Wrapper.m_Menu_ListUp;
        public InputAction @ListDown => m_Wrapper.m_Menu_ListDown;
        public InputAction @MenuSelect => m_Wrapper.m_Menu_MenuSelect;
        public InputAction @Exit => m_Wrapper.m_Menu_Exit;
        public InputActionMap Get() { return m_Wrapper.m_Menu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MenuActions set) { return set.Get(); }
        public void AddCallbacks(IMenuActions instance)
        {
            if (instance == null || m_Wrapper.m_MenuActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MenuActionsCallbackInterfaces.Add(instance);
            @ListUp.started += instance.OnListUp;
            @ListUp.performed += instance.OnListUp;
            @ListUp.canceled += instance.OnListUp;
            @ListDown.started += instance.OnListDown;
            @ListDown.performed += instance.OnListDown;
            @ListDown.canceled += instance.OnListDown;
            @MenuSelect.started += instance.OnMenuSelect;
            @MenuSelect.performed += instance.OnMenuSelect;
            @MenuSelect.canceled += instance.OnMenuSelect;
            @Exit.started += instance.OnExit;
            @Exit.performed += instance.OnExit;
            @Exit.canceled += instance.OnExit;
        }

        private void UnregisterCallbacks(IMenuActions instance)
        {
            @ListUp.started -= instance.OnListUp;
            @ListUp.performed -= instance.OnListUp;
            @ListUp.canceled -= instance.OnListUp;
            @ListDown.started -= instance.OnListDown;
            @ListDown.performed -= instance.OnListDown;
            @ListDown.canceled -= instance.OnListDown;
            @MenuSelect.started -= instance.OnMenuSelect;
            @MenuSelect.performed -= instance.OnMenuSelect;
            @MenuSelect.canceled -= instance.OnMenuSelect;
            @Exit.started -= instance.OnExit;
            @Exit.performed -= instance.OnExit;
            @Exit.canceled -= instance.OnExit;
        }

        public void RemoveCallbacks(IMenuActions instance)
        {
            if (m_Wrapper.m_MenuActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMenuActions instance)
        {
            foreach (var item in m_Wrapper.m_MenuActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MenuActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MenuActions @Menu => new MenuActions(this);
    public interface IPlayerActions
    {
        void OnLine1Action(InputAction.CallbackContext context);
        void OnLine2Action(InputAction.CallbackContext context);
        void OnLine3Action(InputAction.CallbackContext context);
        void OnLine4Action(InputAction.CallbackContext context);
    }
    public interface IFreePlayActions
    {
        void OnListUp(InputAction.CallbackContext context);
        void OnListDown(InputAction.CallbackContext context);
        void OnSongSelect(InputAction.CallbackContext context);
        void OnExitSongList(InputAction.CallbackContext context);
        void OnSpeedUp(InputAction.CallbackContext context);
        void OnSpeedDown(InputAction.CallbackContext context);
    }
    public interface IMenuActions
    {
        void OnListUp(InputAction.CallbackContext context);
        void OnListDown(InputAction.CallbackContext context);
        void OnMenuSelect(InputAction.CallbackContext context);
        void OnExit(InputAction.CallbackContext context);
    }
}
